name: Test de workflow
on:
  workflow_dispatch:
  # schedule:
    # - cron: "0 * * * *"
  
jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - name: Affichage récupération du code source
        run: echo "Récupération du code source"
        
      - name: Affichage vérification terminée
        run: echo "Vérification terminée"
